-- H2 2.4.240; 
;              
CREATE USER IF NOT EXISTS "SA" SALT '7de5e584d09bf41e' HASH 'd4fcb295e03349b06163ffcc0906e90d6e94822c9ea54e2dd62bf6e387a6e03d' ADMIN;          
CREATE SEQUENCE "PUBLIC"."INVENTORY_SEQ" START WITH 1 RESTART WITH 101 INCREMENT BY 50;        
CREATE SEQUENCE "PUBLIC"."NOTIFICATIONS_SEQ" START WITH 1 RESTART WITH 51 INCREMENT BY 50;     
CREATE SEQUENCE "PUBLIC"."ORDERS_SEQ" START WITH 1 RESTART WITH 51 INCREMENT BY 50;            
CREATE SEQUENCE "PUBLIC"."USERS_SEQ" START WITH 1 RESTART WITH 51 INCREMENT BY 50;             
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_USERS"(
    "ID" INTEGER,
    "RN_" INTEGER NOT NULL,
    "CREATEDAT" TIMESTAMP(6),
    "UPDATEDAT" TIMESTAMP(6),
    "EMAIL" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255)
);         
ALTER TABLE "PUBLIC"."HTE_USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" PRIMARY KEY("RN_");    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_USERS;
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_INVENTORY"(
    "COUNT" INTEGER,
    "ID" INTEGER,
    "RN_" INTEGER NOT NULL,
    "CREATEDAT" TIMESTAMP(6),
    "UPDATEDAT" TIMESTAMP(6),
    "CATEGORY" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255)
);             
ALTER TABLE "PUBLIC"."HTE_INVENTORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("RN_");
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_INVENTORY;            
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_ORDERS"(
    "ID" INTEGER,
    "ITEMCOUNT" INTEGER,
    "ITEMID" INTEGER,
    "RN_" INTEGER NOT NULL,
    "CREATEDAT" TIMESTAMP(6),
    "UPDATEDAT" TIMESTAMP(6),
    "STATUS" CHARACTER VARYING(255)
);           
ALTER TABLE "PUBLIC"."HTE_ORDERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("RN_");   
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_ORDERS;               
CREATE GLOBAL TEMPORARY TABLE "PUBLIC"."HTE_NOTIFICATIONS"(
    "ID" INTEGER,
    "RN_" INTEGER NOT NULL,
    "CREATEDAT" TIMESTAMP(6),
    "UPDATEDAT" TIMESTAMP(6),
    "MESSAGE" CHARACTER VARYING(255),
    "STATUS" CHARACTER VARYING(255)
);             
ALTER TABLE "PUBLIC"."HTE_NOTIFICATIONS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_C" PRIMARY KEY("RN_");            
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.HTE_NOTIFICATIONS;        
CREATE MEMORY TABLE "PUBLIC"."EVENT_PUBLICATION"(
    "COMPLETION_ATTEMPTS" INTEGER NOT NULL,
    "COMPLETION_DATE" TIMESTAMP(6) WITH TIME ZONE,
    "LAST_RESUBMISSION_DATE" TIMESTAMP(6) WITH TIME ZONE,
    "PUBLICATION_DATE" TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    "ID" UUID NOT NULL,
    "EVENT_TYPE" CHARACTER VARYING(255) NOT NULL,
    "LISTENER_ID" CHARACTER VARYING(255) NOT NULL,
    "SERIALIZED_EVENT" CHARACTER VARYING(255) NOT NULL,
    "STATUS" ENUM('COMPLETED', 'FAILED', 'PROCESSING', 'PUBLISHED', 'RESUBMITTED')
);             
ALTER TABLE "PUBLIC"."EVENT_PUBLICATION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID");             
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.EVENT_PUBLICATION;        
INSERT INTO "PUBLIC"."EVENT_PUBLICATION" VALUES
(2, TIMESTAMP WITH TIME ZONE '2026-06-28 16:29:08.096956+00', TIMESTAMP WITH TIME ZONE '2026-06-28 16:29:08.088407+00', TIMESTAMP WITH TIME ZONE '2026-06-28 16:29:06.078288+00', UUID 'c9dcaaa6-d899-4c38-9249-434def8bf223', 'com.wiredbarrack.modulith_exploration.orders.dto.OrderPlaced', 'com.wiredbarrack.modulith_exploration.notifications.internal.OrderEventListener.onOrderPlaced(com.wiredbarrack.modulith_exploration.orders.dto.OrderPlaced)', '{"id":99}', 'COMPLETED');       
CREATE MEMORY TABLE "PUBLIC"."INVENTORY"(
    "COUNT" INTEGER,
    "ID" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6),
    "CATEGORY" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255)
);            
ALTER TABLE "PUBLIC"."INVENTORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");     
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.INVENTORY;
INSERT INTO "PUBLIC"."INVENTORY" VALUES
(4, 1, TIMESTAMP '2026-06-28 21:59:01.78749', TIMESTAMP '2026-06-28 21:59:01.787546', 'SWEETS', 'ice cream'),
(45, 2, TIMESTAMP '2026-06-28 21:59:01.797171', TIMESTAMP '2026-06-28 21:59:01.797201', 'BEVERAGES', 'tea');             
CREATE MEMORY TABLE "PUBLIC"."NOTIFICATIONS"(
    "ID" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6),
    "MESSAGE" CHARACTER VARYING(255),
    "STATUS" CHARACTER VARYING(255)
);            
ALTER TABLE "PUBLIC"."NOTIFICATIONS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_5" PRIMARY KEY("ID"); 
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.NOTIFICATIONS;            
INSERT INTO "PUBLIC"."NOTIFICATIONS" VALUES
(1, TIMESTAMP '2026-06-28 21:59:01.804478', TIMESTAMP '2026-06-28 21:59:01.804504', 'Order is delivered', 'PENDING');              
CREATE MEMORY TABLE "PUBLIC"."ORDERS"(
    "ID" INTEGER NOT NULL,
    "ITEM_COUNT" INTEGER,
    "ITEM_ID" INTEGER,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6),
    "STATUS" CHARACTER VARYING(255)
);        
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8B" PRIMARY KEY("ID");       
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.ORDERS;   
INSERT INTO "PUBLIC"."ORDERS" VALUES
(1, NULL, 1, TIMESTAMP '2026-06-28 21:59:01.802252', TIMESTAMP '2026-06-28 21:59:01.802273', 'DELIVERED');
CREATE MEMORY TABLE "PUBLIC"."USERS"(
    "ID" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6),
    "EMAIL" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255)
);        
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");         
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.USERS;    
INSERT INTO "PUBLIC"."USERS" VALUES
(1, TIMESTAMP '2026-06-28 21:59:01.80006', TIMESTAMP '2026-06-28 21:59:01.800083', 'vineet.wiredbarrack@gmail.com', 'Vineet');             
