-- H2 2.2.224; 
;              
CREATE USER IF NOT EXISTS "SA" SALT 'b2da89a3326a6539' HASH 'e2fdeef98e85dddb0f541650b001d0bd1a817bedf25c797bbc37182c7b6ec574' ADMIN;          
CREATE SEQUENCE "PUBLIC"."INVENTORY_SEQ" START WITH 1 RESTART WITH 101 INCREMENT BY 50;        
CREATE SEQUENCE "PUBLIC"."NOTIFICATION_SEQ" START WITH 1 RESTART WITH 51 INCREMENT BY 50;      
CREATE SEQUENCE "PUBLIC"."ORDERS_SEQ" START WITH 1 RESTART WITH 51 INCREMENT BY 50;            
CREATE SEQUENCE "PUBLIC"."USERS_SEQ" START WITH 1 RESTART WITH 51 INCREMENT BY 50;             
CREATE MEMORY TABLE "PUBLIC"."EVENT_PUBLICATION"(
    "COMPLETION_DATE" TIMESTAMP(6) WITH TIME ZONE,
    "PUBLICATION_DATE" TIMESTAMP(6) WITH TIME ZONE,
    "ID" UUID NOT NULL,
    "EVENT_TYPE" CHARACTER VARYING(255),
    "LISTENER_ID" CHARACTER VARYING(255),
    "SERIALIZED_EVENT" CHARACTER VARYING(255)
);           
ALTER TABLE "PUBLIC"."EVENT_PUBLICATION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID");             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.EVENT_PUBLICATION;        
CREATE MEMORY TABLE "PUBLIC"."INVENTORY"(
    "COUNT" INTEGER,
    "ID" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6),
    "CATEGORY" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255)
);            
ALTER TABLE "PUBLIC"."INVENTORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");     
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.INVENTORY;
INSERT INTO "PUBLIC"."INVENTORY" VALUES
(4, 1, TIMESTAMP '2026-05-17 15:55:25.99898', TIMESTAMP '2026-05-17 15:55:25.999009', 'SWEETS', 'ice cream'),
(45, 2, TIMESTAMP '2026-05-17 15:55:25.999545', TIMESTAMP '2026-05-17 15:55:25.999561', 'BEVERAGES', 'tea');             
CREATE MEMORY TABLE "PUBLIC"."NOTIFICATION"(
    "ID" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6),
    "MESSAGE" CHARACTER VARYING(255),
    "STATUS" CHARACTER VARYING(255)
);             
ALTER TABLE "PUBLIC"."NOTIFICATION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" PRIMARY KEY("ID");  
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.NOTIFICATION;             
INSERT INTO "PUBLIC"."NOTIFICATION" VALUES
(1, TIMESTAMP '2026-05-17 15:55:25.995399', TIMESTAMP '2026-05-17 15:55:25.995426', 'Order is delivered', 'PENDING');               
CREATE MEMORY TABLE "PUBLIC"."ORDERS"(
    "ID" INTEGER NOT NULL,
    "ITEM_COUNT" INTEGER,
    "ITEM_ID" INTEGER,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6),
    "STATUS" CHARACTER VARYING(255)
);        
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID");        
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.ORDERS;   
INSERT INTO "PUBLIC"."ORDERS" VALUES
(1, NULL, 1, TIMESTAMP '2026-05-17 15:55:26.001522', TIMESTAMP '2026-05-17 15:55:26.00154', 'DELIVERED'); 
CREATE MEMORY TABLE "PUBLIC"."USERS"(
    "ID" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6),
    "EMAIL" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255)
);        
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");         
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.USERS;    
INSERT INTO "PUBLIC"."USERS" VALUES
(1, TIMESTAMP '2026-05-17 15:55:25.983348', TIMESTAMP '2026-05-17 15:55:25.983505', 'vineet.wiredbarrack@gmail.com', 'Vineet');            
