-- H2 2.2.224; 
;              
CREATE USER IF NOT EXISTS "SA" SALT '081770ae49184cd7' HASH 'ebf378101534ee7f1b5860a03d17c5ddda58b74921f365aeaffecd02def30b41' ADMIN;          
CREATE SEQUENCE "PUBLIC"."INVENTORY_SEQ" START WITH 1 RESTART WITH 101 INCREMENT BY 50;        
CREATE SEQUENCE "PUBLIC"."NOTIFICATION_SEQ" START WITH 1 RESTART WITH 51 INCREMENT BY 50;      
CREATE SEQUENCE "PUBLIC"."ORDERS_SEQ" START WITH 1 RESTART WITH 51 INCREMENT BY 50;            
CREATE SEQUENCE "PUBLIC"."USERS_SEQ" START WITH 1 RESTART WITH 51 INCREMENT BY 50;             
CREATE MEMORY TABLE "PUBLIC"."EVENT_PUBLICATION"(
    "COMPLETION_DATE" TIMESTAMP(6) WITH TIME ZONE,
    "PUBLICATION_DATE" TIMESTAMP(6) WITH TIME ZONE,
    "ID" UUID NOT NULL,
    "EVENT_TYPE" CHARACTER VARYING(255),
    "LISTENER_ID" CHARACTER VARYING(255),
    "SERIALIZED_EVENT" CHARACTER VARYING(255)
);           
ALTER TABLE "PUBLIC"."EVENT_PUBLICATION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID");             
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.EVENT_PUBLICATION;        
CREATE MEMORY TABLE "PUBLIC"."INVENTORY"(
    "COUNT" INTEGER,
    "ID" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6),
    "CATEGORY" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255)
);            
ALTER TABLE "PUBLIC"."INVENTORY" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");     
-- 2 +/- SELECT COUNT(*) FROM PUBLIC.INVENTORY;
INSERT INTO "PUBLIC"."INVENTORY" VALUES
(4, 1, TIMESTAMP '2026-05-17 19:31:25.96555', TIMESTAMP '2026-05-17 19:31:25.965575', 'SWEETS', 'ice cream'),
(45, 2, TIMESTAMP '2026-05-17 19:31:25.966015', TIMESTAMP '2026-05-17 19:31:25.966028', 'BEVERAGES', 'tea');             
CREATE MEMORY TABLE "PUBLIC"."NOTIFICATION"(
    "ID" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6),
    "MESSAGE" CHARACTER VARYING(255),
    "STATUS" CHARACTER VARYING(255)
);             
ALTER TABLE "PUBLIC"."NOTIFICATION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" PRIMARY KEY("ID");  
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.NOTIFICATION;             
INSERT INTO "PUBLIC"."NOTIFICATION" VALUES
(1, TIMESTAMP '2026-05-17 19:31:25.969087', TIMESTAMP '2026-05-17 19:31:25.969103', 'Order is delivered', 'PENDING');               
CREATE MEMORY TABLE "PUBLIC"."ORDERS"(
    "ID" INTEGER NOT NULL,
    "ITEM_COUNT" INTEGER,
    "ITEM_ID" INTEGER,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6),
    "STATUS" CHARACTER VARYING(255)
);        
ALTER TABLE "PUBLIC"."ORDERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID");        
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.ORDERS;   
INSERT INTO "PUBLIC"."ORDERS" VALUES
(1, NULL, 1, TIMESTAMP '2026-05-17 19:31:25.967532', TIMESTAMP '2026-05-17 19:31:25.967545', 'DELIVERED');
CREATE MEMORY TABLE "PUBLIC"."USERS"(
    "ID" INTEGER NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "UPDATED_AT" TIMESTAMP(6),
    "EMAIL" CHARACTER VARYING(255),
    "NAME" CHARACTER VARYING(255)
);        
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");         
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.USERS;    
INSERT INTO "PUBLIC"."USERS" VALUES
(1, TIMESTAMP '2026-05-17 19:31:25.955384', TIMESTAMP '2026-05-17 19:31:25.955518', 'vineet.wiredbarrack@gmail.com', 'Vineet');            
